### ISSUE TITLE
glsl files inside node_modules

### ISSUE THREAD

**Issue by tiye** [UstymUkhman/vite-plugin-glsl#18]
I ran into a case I bundled my TypeScript and GLSL files into an npm module, and got it loaded in another project. Then it turned out GLSL files inside the module are not loaded correctly. Was this plugin supposed to be used for files inside `node_modules/`, or any quick options I could use to fix that?

<details>

```
=>> yarn vite --host=0.0.0.0
yarn run v1.22.19
$ /Users/me/repo/triadica/ts-workflow/node_modules/.bin/vite --host=0.0.0.0

  VITE v3.0.5  ready in 104 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: http://192.168.31.28:5173/
✘ [ERROR] No loader is configured for ".frag" files: node_modules/triadica/shaders/effect-mix.frag

    node_modules/triadica/src/index.mts:11:26:
      11 │ import effectMixFrag from "../shaders/effect-mix.frag";
         ╵                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] No loader is configured for ".glsl" files: node_modules/triadica/shaders/triadica-colors.glsl

    node_modules/triadica/src/config.mts:37:27:
      37 │ ...t glslColorsCode from "../shaders/triadica-colors.glsl";
         ╵                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] No loader is configured for ".glsl" files: node_modules/triadica/shaders/triadica-perspective.glsl

    node_modules/triadica/src/config.mts:26:32:
      26 │ ...pectiveCode from "../shaders/triadica-perspective.glsl";
         ╵                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] No loader is configured for ".frag" files: node_modules/triadica/shaders/effect-x.frag

    node_modules/triadica/src/index.mts:9:24:
      9 │ import effectXFrag from "../shaders/effect-x.frag";
        ╵                         ~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] No loader is configured for ".glsl" files: node_modules/triadica/shaders/triadica-rotation.glsl

    node_modules/triadica/src/config.mts:28:29:
      28 │ ...slRotationCode from "../shaders/triadica-rotation.glsl";
         ╵                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] No loader is configured for ".vert" files: node_modules/triadica/shaders/effect-x.vert

    node_modules/triadica/src/index.mts:8:24:
      8 │ import effectXVert from "../shaders/effect-x.vert";
        ╵                         ~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] No loader is configured for ".glsl" files: node_modules/triadica/shaders/triadica-noises.glsl

    node_modules/triadica/src/config.mts:27:27:
      27 │ ...t glslNoisesCode from "../shaders/triadica-noises.glsl";
         ╵                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] No loader is configured for ".vert" files: node_modules/triadica/shaders/effect-mix.vert

    node_modules/triadica/src/index.mts:10:26:
      10 │ import effectMixVert from "../shaders/effect-mix.vert";
         ╵                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

12:28:25 PM [vite] error while updating dependencies:
Error: Build failed with 8 errors:
node_modules/triadica/src/config.mts:26:32: ERROR: No loader is configured for ".glsl" files: node_modules/triadica/shaders/triadica-perspective.glsl
node_modules/triadica/src/config.mts:27:27: ERROR: No loader is configured for ".glsl" files: node_modules/triadica/shaders/triadica-noises.glsl
node_modules/triadica/src/config.mts:28:29: ERROR: No loader is configured for ".glsl" files: node_modules/triadica/shaders/triadica-rotation.glsl
node_modules/triadica/src/config.mts:37:27: ERROR: No loader is configured for ".glsl" files: node_modules/triadica/shaders/triadica-colors.glsl
node_modules/triadica/src/index.mts:8:24: ERROR: No loader is configured for ".vert" files: node_modules/triadica/shaders/effect-x.vert
..
    at failureErrorWithLog (/Users/me/repo/triadica/ts-workflow/node_modules/esbuild/lib/main.js:1624:15)
    at /Users/me/repo/triadica/ts-workflow/node_modules/esbuild/lib/main.js:1266:28
    at runOnEndCallbacks (/Users/me/repo/triadica/ts-workflow/node_modules/esbuild/lib/main.js:1046:63)
    at buildResponseToResult (/Users/me/repo/triadica/ts-workflow/node_modules/esbuild/lib/main.js:1264:7)
    at /Users/me/repo/triadica/ts-workflow/node_modules/esbuild/lib/main.js:1377:14
    at /Users/me/repo/triadica/ts-workflow/node_modules/esbuild/lib/main.js:678:9
    at handleIncomingPacket (/Users/me/repo/triadica/ts-workflow/node_modules/esbuild/lib/main.js:775:9)
    at Socket.readFromStdout (/Users/me/repo/triadica/ts-workflow/node_modules/esbuild/lib/main.js:644:7)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:324:12)
^C
=>>
```

</details>

Also tried to run `vite build` and it worked correctly with same configuration(default `glsl()`).

----

update: looks like first problem is I was using `mts` directly from my app. I should compile all to `.mjs` and try again.

----

update: I can get it work by specifying `optimizeDeps.exclude` to disable ops.

**Comment by UstymUkhman** [comment]
Hi @tiye and thanks for opening this issue. I was able to reproduce it and I think your workaround is actually correct since as described by [Vite documentation](https://vitejs.dev/guide/dep-pre-bundling.html#customizing-the-behavior):

> A typical use case for `optimizeDeps.include` or `optimizeDeps.exclude` is when you have an import that is not directly discoverable in the source code. For example, maybe the import is created as a result of a plugin transform.

In my case I just had to add

```
optimizeDeps: {
  exclude: ['<PACKAGE_NAME_THAT_IMPORTS_SHADERS>']
},
```

in `vite.config.js` of the project that was requiring a file from `node_modules/` that was actually importing some shaders. Is that similar to your fix? Do you have any other questions I can help you with?

Please let me know if this approach with `optimizeDeps` sounds plausible to you so I can consider this issue solved.
P.S.: Please consider ⭐ing this plugin if in your opinion it does a decent job for your purposes. Thanks.

Cheers!

**Comment by tiye** [comment]
it doesn't look like a perfect solution, but I can stand with it.
